# Generated by Django 4.2.7 on 2023-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanasi', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
